name: your_career_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  go_router: ^15.2.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.1
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
